#!/usr/bin/env bash

echo "Creating database fpc..."
pgmgr db create

echo "Running migrations..."
pgmgr db migrate

echo "Creating database fpc-test"
pgmgr -c ".pgmgr.test.json" db create

echo "Running migration on postgres://nickc@localhost:5432/fpc-test?sslmode=disable&password=postgres..."
pgmgr -c ".pgmgr.test.json" db migrate
